"""Constants for the FortiGate Policy Presence integration."""

from datetime import timedelta

DOMAIN = "fortigate_policy"

CONF_API_TOKEN = "api_token"
CONF_VDOM = "vdom"
CONF_POLICY_ID = "policy_id"
CONF_POLICY_NAME = "policy_name"
CONF_POLICY_IDS = "policy_ids"
CONF_POLICIES = "policies"
CONF_LEGACY_PRIMARY_POLICY_ID = "legacy_primary_policy_id"
CONF_VERIFY_SSL = "verify_ssl"
CONF_POLL_INTERVAL = "poll_interval"
CONF_WIFI_TRACKING_ENABLED = "wifi_tracking_enabled"
CONF_WIFI_POLL_INTERVAL = "wifi_poll_interval"
CONF_WIFI_AWAY_GRACE_PERIOD = "wifi_away_grace_period"
CONF_WIFI_CLIENT_COUNT_SENSOR = "wifi_client_count_sensor"
CONF_NETWORK_TRACK_FORTIAP_CLIENTS = "network_track_fortiap_clients"
CONF_NETWORK_CREATE_TRACKER_ENTITIES = "network_create_tracker_entities"
CONF_NETWORK_NEW_DEVICE_DETECTION = "network_new_device_detection"
CONF_TRACKED_CLIENTS = "tracked_clients"
CONF_RECENT_WIFI_CLIENTS = "recent_wifi_clients"
CONF_FRIENDLY_NAME = "friendly_name"
CONF_ALLOWED_SSIDS = "allowed_ssids"
CONF_PRESENCE_POLICY_RULES = "presence_policy_rules"
CONF_PRESENCE_USERS = "presence_users"
CONF_PRESENCE_USER_ID = "presence_user_id"
CONF_PRESENCE_USER_NAME = "presence_user_name"
CONF_PRESENCE_USER_MACS = "presence_user_macs"
CONF_PRESENCE_USERS_TO_REMOVE = "presence_users_to_remove"
CONF_USER_AWAY_GRACE_PERIOD = "user_away_grace_period"
CONF_RECENT_CLIENT_RETENTION_DAYS = "recent_client_retention_days"

DEFAULT_PORT = 443
DEFAULT_VDOM = "root"
DEFAULT_VERIFY_SSL = True
DEFAULT_POLL_INTERVAL = 60
DEFAULT_TIMEOUT = 10
MIN_POLL_INTERVAL = 30
MAX_POLL_INTERVAL = 3600

DEFAULT_WIFI_TRACKING_ENABLED = False
DEFAULT_WIFI_POLL_INTERVAL = 30
DEFAULT_WIFI_AWAY_GRACE_PERIOD = 300
MIN_WIFI_POLL_INTERVAL = 15
MAX_WIFI_POLL_INTERVAL = 120
MIN_WIFI_AWAY_GRACE_PERIOD = 30
MAX_WIFI_AWAY_GRACE_PERIOD = 3600
DEFAULT_WIFI_CLIENT_COUNT_SENSOR = False
DEFAULT_NETWORK_TRACK_FORTIAP_CLIENTS = True
DEFAULT_NETWORK_CREATE_TRACKER_ENTITIES = True
DEFAULT_NETWORK_NEW_DEVICE_DETECTION = True
MAX_RECENT_WIFI_CLIENTS = 100
MAX_STORED_NETWORK_CLIENTS = 1000
DEFAULT_USER_AWAY_GRACE_PERIOD = 180
DEFAULT_RECENT_CLIENT_RETENTION_DAYS = 30
MIN_USER_AWAY_GRACE_PERIOD = 30
MAX_USER_AWAY_GRACE_PERIOD = 7200
MAX_RECENT_CLIENT_RETENTION_DAYS = 365

STATUS_ENABLE = "enable"
STATUS_DISABLE = "disable"
VALID_STATUSES = frozenset({STATUS_ENABLE, STATUS_DISABLE})

EVENT_NEW_NETWORK_DEVICE = "fortigate_new_network_device"
NETWORK_CONNECTION_WIFI = "wifi"
NETWORK_SOURCE_FORTIAP = "fortiap"

UPDATE_RETRIES = 3
UPDATE_RETRY_DELAY = timedelta(seconds=2)
