"""Constants for the FortiGate Policy Presence integration."""

from datetime import timedelta

DOMAIN = "fortigate_policy"

CONF_API_TOKEN = "api_token"
CONF_VDOM = "vdom"
CONF_POLICY_ID = "policy_id"
CONF_POLICY_NAME = "policy_name"
CONF_POLICY_IDS = "policy_ids"
CONF_POLICIES = "policies"
CONF_LEGACY_PRIMARY_POLICY_ID = "legacy_primary_policy_id"
CONF_VERIFY_SSL = "verify_ssl"
CONF_POLL_INTERVAL = "poll_interval"
CONF_WIFI_TRACKING_ENABLED = "wifi_tracking_enabled"
CONF_WIFI_POLL_INTERVAL = "wifi_poll_interval"
CONF_WIFI_AWAY_GRACE_PERIOD = "wifi_away_grace_period"
CONF_WIFI_CLIENT_COUNT_SENSOR = "wifi_client_count_sensor"
CONF_TRACKED_CLIENTS = "tracked_clients"
CONF_RECENT_WIFI_CLIENTS = "recent_wifi_clients"
CONF_FRIENDLY_NAME = "friendly_name"
CONF_ALLOWED_SSIDS = "allowed_ssids"
CONF_PRESENCE_POLICY_RULES = "presence_policy_rules"
CONF_RULE_TRACKER = "rule_tracker"
CONF_PRESENCE_USERS = "presence_users"
CONF_PRESENCE_USER_ID = "presence_user_id"
CONF_PRESENCE_USER_NAME = "presence_user_name"
CONF_PRESENCE_USER_MACS = "presence_user_macs"
CONF_PRESENCE_USERS_TO_REMOVE = "presence_users_to_remove"
CONF_USER_AWAY_GRACE_PERIOD = "user_away_grace_period"
CONF_HOME_ENABLE_POLICIES = "home_enable_policies"
CONF_HOME_DISABLE_POLICIES = "home_disable_policies"
CONF_AWAY_ENABLE_POLICIES = "away_enable_policies"
CONF_AWAY_DISABLE_POLICIES = "away_disable_policies"
CONF_POLICY_AUTOMATION_ENABLED = "policy_automation_enabled"
CONF_POLICY_AUTOMATION_DRY_RUN = "policy_automation_dry_run"
CONF_DEFAULT_OVERRIDE_MINUTES = "default_override_minutes"
CONF_POLICY_RULES_V2 = "policy_rules_v2"
CONF_POLICY_RULE_ID = "policy_rule_id"
CONF_POLICY_RULE_NAME = "policy_rule_name"
CONF_POLICY_RULE_USERS = "policy_rule_users"
CONF_POLICY_RULE_MATCH = "policy_rule_match"
CONF_POLICY_RULE_PRESENCE = "policy_rule_presence"
CONF_POLICY_RULE_ACTION = "policy_rule_action"
CONF_POLICY_RULE_POLICIES = "policy_rule_policies"
CONF_POLICY_RULE_PRIORITY = "policy_rule_priority"
CONF_POLICY_RULE_SCHEDULE = "policy_rule_schedule"
CONF_POLICY_RULES_TO_REMOVE = "policy_rules_to_remove"
CONF_RECENT_CLIENT_RETENTION_DAYS = "recent_client_retention_days"

DEFAULT_PORT = 443
DEFAULT_VDOM = "root"
DEFAULT_VERIFY_SSL = True
DEFAULT_POLL_INTERVAL = 60
DEFAULT_TIMEOUT = 10
MIN_POLL_INTERVAL = 30
MAX_POLL_INTERVAL = 3600

DEFAULT_WIFI_TRACKING_ENABLED = False
DEFAULT_WIFI_POLL_INTERVAL = 30
DEFAULT_WIFI_AWAY_GRACE_PERIOD = 180
MIN_WIFI_POLL_INTERVAL = 15
MAX_WIFI_POLL_INTERVAL = 120
MIN_WIFI_AWAY_GRACE_PERIOD = 30
MAX_WIFI_AWAY_GRACE_PERIOD = 3600
DEFAULT_WIFI_CLIENT_COUNT_SENSOR = False
MAX_RECENT_WIFI_CLIENTS = 100
DEFAULT_USER_AWAY_GRACE_PERIOD = 180
DEFAULT_POLICY_AUTOMATION_ENABLED = True
DEFAULT_POLICY_AUTOMATION_DRY_RUN = False
DEFAULT_OVERRIDE_MINUTES = 60
DEFAULT_RECENT_CLIENT_RETENTION_DAYS = 30
MIN_USER_AWAY_GRACE_PERIOD = 30
MAX_USER_AWAY_GRACE_PERIOD = 7200
MAX_OVERRIDE_MINUTES = 1440
MAX_RECENT_CLIENT_RETENTION_DAYS = 365

RULE_MATCH_ANY = "any"
RULE_MATCH_ALL = "all"
RULE_PRESENCE_HOME = "home"
RULE_PRESENCE_AWAY = "away"
OVERRIDE_AUTOMATIC = "automatic"
OVERRIDE_FORCE_ENABLE = "force_enable"
OVERRIDE_FORCE_DISABLE = "force_disable"
OVERRIDE_PAUSED = "paused"
OVERRIDE_MODES = (
    OVERRIDE_AUTOMATIC,
    OVERRIDE_FORCE_ENABLE,
    OVERRIDE_FORCE_DISABLE,
    OVERRIDE_PAUSED,
)

STATUS_ENABLE = "enable"
STATUS_DISABLE = "disable"
VALID_STATUSES = frozenset({STATUS_ENABLE, STATUS_DISABLE})

UPDATE_RETRIES = 3
UPDATE_RETRY_DELAY = timedelta(seconds=2)
